version: '3'

services: 
  web: 
    container_name: nginx
    build: 
      context: ./
      dockerfile: web.dockerfile
    # network_mode: host
    volumes:
      - ./:/var/www/html/s_crm
    ports:
      - "9090:80"
    
    
      
    links:
      - app

      
  app: 
    container_name: scrm
    restart: always
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./:/var/www/html/s_crm
      - /var/www/html/s_crm/vendor
    

